def getData():
    import requests
    url = "http://dsebd.org/day_end_archive.php"
    payload = {'DayEndSumDate1' : '2016-09-01',
                   'DayEndSumDate1_dp' : '1',
                   'DayEndSumDate1_year_start' : '2014' ,
                   'DayEndSumDate1_year_end' : '2016' ,
                   'DayEndSumDate1_sna' : '1' ,
                   'DayEndSumDate1_inp' : '1' ,
                   'DayEndSumDate1_fmt' : 'j+F+Y' ,
                   'DayEndSumDate1_pth' : 'calendar%2F' ,
                   'DayEndSumDate1_spd' : '%5B%5B%5D%2C%5B%5D%2C%5B%5D%5D' ,
                   'DayEndSumDate1_spt' : '0' ,
                   'DayEndSumDate1_str' : '0' ,
                   'DayEndSumDate1_int' : '1' , 
                   'DayEndSumDate1_hid' : '1' ,
                   'DayEndSumDate1_hdt' : '1000' ,
                   'DayEndSumDate1_day' : '01' ,
                   'DayEndSumDate1_month' : '09' ,
                   'DayEndSumDate1_year' : '2016' ,
                   'DayEndSumDate2' : '2016-09-18' ,
                   'DayEndSumDate2_dp' : '1' ,
                   'DayEndSumDate2_year_start' : '2014' ,
                   'DayEndSumDate2_year_end' : '2016' ,
                   'DayEndSumDate2_sna' : '1' ,
                   'DayEndSumDate2_inp' : '1' ,
                   'DayEndSumDate2_fmt' : 'j+F+Y' ,
                   'DayEndSumDate2_pth' : 'calendar%2F' ,
                   'DayEndSumDate2_spd' : '%5B%5B%5D%2C%5B%5D%2C%5B%5D%5D' ,
                   'DayEndSumDate2_spt' : '0' ,
                   'DayEndSumDate2_str' : '0' , 
                   'DayEndSumDate2_int' : '1' ,
                   'DayEndSumDate2_hid' : '1' ,
                   'DayEndSumDate2_hdt' : '1000' ,
                   'DayEndSumDate2_day' : '18' ,
                   'DayEndSumDate2_month' : '09' ,
                   'DayEndSumDate2_year' : '2016' ,
                   'Symbol' : '1JANATAMF' ,
                   'ViewDayEndArchive' : 'View+Day+End+Archive'}
    r = requests.post(url, data = payload)
